name = "rbicc"
main = "worker.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "rbicc-db"
database_id = "fc150e81-dbba-49d8-9624-67cd891ccec0"

[vars]
GITHUB_REPO = "Remi-ai-git/rbicc"
